manifest:
  self:
    path: modules/ec

  remotes:
    - name: chromium
      url-base: https://chromium.googlesource.com/chromiumos

  projects:
    - name: zephyr
      remote: chromium
      repo-path: third_party/zephyr
      revision: main
      path: zephyr
      west-commands: scripts/west-commands.yml
      clone-depth: 500

    - name: cmsis
      remote: chromium
      repo-path: third_party/zephyr/cmsis
      revision: chromeos-main
      path: modules/cmsis
      clone-depth: 500

    - name: hal_stm32
      remote: chromium
      repo-path: third_party/zephyr/hal_stm32
      revision: chromeos-main
      path: modules/hal_stm32
      clone-depth: 500

    - name: nanopb
      remote: chromium
      repo-path: third_party/zephyr/nanopb
      revision: main
      path: modules/nanopb
      clone-depth: 500

    - name: cryptoc
      remote: chromium
      repo-path: third_party/cryptoc
      revision: main
      path: modules/cryptoc
      clone-depth: 500
